TIER_2_INDUSTRIES = [
    {
        "industry_name": "Environmental Consulting",
        "synonyms": ["Environmental Services", "Environmental Engineers", "Eco-Consultants", "Environmental Assessment Firms"],
        "top_workers_comp_claims": [
            "Chemical exposure during soil or water sampling at contaminated sites",
            "Slip/fall injuries on uneven terrain during field assessments",
            "Respiratory illness from prolonged exposure to airborne contaminants",
        ],
        "commercial_auto_claims": [
            "Vehicle accidents while traveling to remote field investigation sites",
            "Equipment damage during transport of sampling and monitoring gear",
        ],
        "general_liability_exposures": [
            "Errors in environmental site assessments leading to third-party property damage",
            "Pollution conditions arising from recommended remediation procedures",
            "Failure to identify contamination resulting in regulatory fines for clients",
            "Bodily injury to bystanders during drilling or excavation activities",
        ],
        "conversation_prompts": [
            "Do you perform Phase I and Phase II environmental site assessments, and what percentage of revenue comes from each?",
            "Are your field staff working on active Superfund or brownfield sites with known contamination?",
            "Do you carry professional liability (E&O) coverage separate from your GL policy?",
            "What personal protective equipment protocols do you have in place for field personnel?",
        ],
        "regional_risk_notes": "Coastal and industrial corridor states (NJ, TX, LA, CA) have higher demand and greater exposure to legacy contamination sites. States with aggressive environmental enforcement (CA, NY) increase professional liability risk.",
    },
    {
        "industry_name": "Waste Management / Hauling",
        "synonyms": ["Trash Hauling", "Solid Waste Collection", "Refuse Services", "Garbage Collection", "Waste Disposal"],
        "top_workers_comp_claims": [
            "Musculoskeletal injuries from repetitive lifting and loading of heavy containers",
            "Struck-by injuries from moving vehicles or compaction equipment",
            "Needlestick or sharps injuries from improperly disposed medical waste",
            "Crush injuries during rear-load or side-load hopper operations",
        ],
        "commercial_auto_claims": [
            "Backing accidents with collection trucks in residential neighborhoods",
            "Rollover incidents on uneven landfill roads or steep grades",
            "Third-party property damage from leaking fluids or debris falling from trucks",
        ],
        "general_liability_exposures": [
            "Property damage from leaking waste containers or hydraulic fluid spills",
            "Pollution liability from landfill runoff or illegal dumping allegations",
            "Bodily injury to pedestrians during curbside collection operations",
        ],
        "conversation_prompts": [
            "What types of waste do you handle — residential, commercial, industrial, or a mix?",
            "Do you own or operate any transfer stations or landfill facilities?",
            "What is the size and age of your fleet, and do you have onboard camera systems?",
            "Are drivers trained on OSHA bloodborne pathogen standards for incidental exposure?",
        ],
        "regional_risk_notes": "Landfill tipping fees and regulations vary dramatically by state, affecting profitability and liability. Northern states face additional slip-and-fall exposure during icy collection months.",
    },
    {
        "industry_name": "Recycling Facilities",
        "synonyms": ["Material Recovery Facilities", "Recycling Centers", "Scrap Processing", "MRF Operations"],
        "top_workers_comp_claims": [
            "Lacerations and puncture wounds from sorting contaminated recyclables",
            "Repetitive motion injuries on manual sorting lines",
            "Hearing loss from prolonged exposure to processing machinery noise",
        ],
        "commercial_auto_claims": [
            "Collisions involving bale trucks or roll-off container haulers",
            "Loading dock accidents during material pickup and delivery",
        ],
        "general_liability_exposures": [
            "Fire and explosion risk from lithium-ion batteries in recycling streams",
            "Environmental contamination from stormwater runoff at outdoor storage yards",
            "Property damage to adjacent businesses from facility fires",
            "Bodily injury to visitors or vendors on sorting facility floors",
        ],
        "conversation_prompts": [
            "Do you process single-stream recyclables, and what contamination rate do you typically see?",
            "What fire suppression and detection systems are installed in your facility?",
            "Have you experienced any fires caused by lithium batteries in your waste stream?",
            "Do you have environmental impairment liability coverage for your site?",
        ],
        "regional_risk_notes": "West Coast facilities face stricter contamination standards following China's National Sword policy impacts. States with bottle deposit laws (OR, MI, CA) create different operational models and exposures.",
    },
    {
        "industry_name": "Hazardous Waste Transport",
        "synonyms": ["Hazmat Hauling", "Hazardous Material Transport", "RCRA Waste Haulers", "Chemical Waste Logistics"],
        "top_workers_comp_claims": [
            "Chemical burns or toxic exposure during spill response and containment",
            "Respiratory injury from inhalation of volatile or corrosive substances",
            "Back injuries from manual handling of drums and containers",
        ],
        "commercial_auto_claims": [
            "Hazmat release following traffic accident requiring emergency response and cleanup",
            "DOT violations and resulting regulatory penalties from improper placarding",
            "Third-party bodily injury or evacuation costs following transport incidents",
        ],
        "general_liability_exposures": [
            "Pollution liability from accidental spills during loading, transit, or unloading",
            "Completed operations exposure from improper disposal at destination facilities",
            "Environmental cleanup costs at third-party sites traced to transported materials",
            "Contractual liability from shipper indemnification agreements",
        ],
        "conversation_prompts": [
            "What UN hazard classes do you transport, and do you handle radioactive or explosive materials?",
            "Are all drivers HAZWOPER-trained and do they carry current CDL with hazmat endorsement?",
            "Do you carry pollution liability and MCS-90 endorsements on your auto policy?",
            "What is your DOT safety rating and your out-of-service rate?",
        ],
        "regional_risk_notes": "Routes through densely populated urban corridors or near watersheds dramatically increase pollution liability exposure. Gulf Coast and Great Lakes regions have heightened regulatory scrutiny for hazmat carriers.",
    },
    {
        "industry_name": "Apartment Complexes",
        "synonyms": ["Multifamily Housing", "Residential Rental Properties", "Apartment Communities", "Multi-Unit Dwellings"],
        "top_workers_comp_claims": [
            "Maintenance staff injuries from slip/fall on wet or icy walkways",
            "Electrical shock during appliance repair or fixture replacement",
            "Strains from carrying heavy appliances or materials up stairwells",
        ],
        "commercial_auto_claims": [
            "Accidents involving maintenance vehicles or courtesy shuttles",
            "Property damage from groundskeeping vehicles on public roadways",
        ],
        "general_liability_exposures": [
            "Premises liability from tenant or visitor slip-and-fall on common areas",
            "Negligent security claims following assaults or break-ins on property",
            "Water damage liability from deferred plumbing maintenance affecting multiple units",
            "Swimming pool drowning or injury claims",
        ],
        "conversation_prompts": [
            "How many units do you manage, and what is the age and construction type of the buildings?",
            "Do you have a swimming pool, playground, or fitness center on the premises?",
            "What security measures are in place — gated entry, cameras, on-site patrol?",
            "Have you had any habitability complaints, bed bug claims, or mold issues in the past three years?",
        ],
        "regional_risk_notes": "Properties in hurricane-prone states (FL, TX, LA) face significant wind and flood exposure, while northern properties deal with ice dam and frozen pipe claims. Tenant-friendly jurisdictions (CA, NY) increase litigation exposure.",
    },
    {
        "industry_name": "Condominium Associations (HOA)",
        "synonyms": ["HOA Management", "Homeowners Associations", "Condo Associations", "Community Associations", "Property Owner Associations"],
        "top_workers_comp_claims": [
            "Groundskeeper injuries from landscaping equipment or chemical application",
            "Maintenance worker falls from ladders during exterior building upkeep",
            "Repetitive strain injuries for on-site office and administrative staff",
        ],
        "commercial_auto_claims": [
            "Accidents involving association-owned maintenance or security patrol vehicles",
            "Property damage during snow removal operations in parking areas",
        ],
        "general_liability_exposures": [
            "Slip-and-fall on common areas including lobbies, pools, and parking structures",
            "Directors and officers liability for board decisions on assessments or rule enforcement",
            "Failure to maintain common elements resulting in unit owner property damage",
            "Discrimination claims related to enforcement of community rules or architectural standards",
        ],
        "conversation_prompts": [
            "How many units are in the association, and is it a high-rise, mid-rise, or townhome community?",
            "Does the board carry D&O liability coverage, and have there been any board-related lawsuits?",
            "What is the association's reserve fund status, and has a recent reserve study been completed?",
            "Are there any shared amenities such as pools, clubhouses, or parking garages?",
        ],
        "regional_risk_notes": "Florida condo associations face unique exposure following structural inspection mandates post-Surfside collapse. Western states with wildfire-urban interface communities have escalating property and liability exposure.",
    },
    {
        "industry_name": "Commercial Property Management",
        "synonyms": ["Property Management Companies", "Commercial Real Estate Management", "Facility Management", "Building Management Services"],
        "top_workers_comp_claims": [
            "Maintenance technician injuries from HVAC, electrical, or plumbing repairs",
            "Security personnel injuries during tenant or trespasser confrontations",
            "Janitorial staff chemical exposure from cleaning products",
        ],
        "commercial_auto_claims": [
            "Accidents involving property managers traveling between managed sites",
            "Maintenance vehicle incidents in parking structures or loading docks",
            "Hired and non-owned auto exposure from employees using personal vehicles",
        ],
        "general_liability_exposures": [
            "Premises liability for injuries to tenants, visitors, or delivery personnel",
            "Errors and omissions in lease administration or CAM reconciliation",
            "Environmental liability for legacy contamination discovered at managed properties",
            "Tenant discrimination allegations under Fair Housing laws",
        ],
        "conversation_prompts": [
            "What types of properties do you manage — office, retail, industrial, or mixed-use?",
            "How many properties and total square footage are under management?",
            "Do your management contracts include indemnification and hold-harmless clauses?",
            "Are you responsible for selecting and overseeing subcontractors for building maintenance?",
        ],
        "regional_risk_notes": "High-cost metro markets (NYC, SF, Chicago) bring elevated liability limits expectations from building owners. Properties in seismic or hurricane zones require specialized coverage coordination between owner and manager policies.",
    },
    {
        "industry_name": "Nonprofit Organizations (General)",
        "synonyms": ["501(c)(3) Organizations", "Charitable Organizations", "NGOs", "Not-for-Profit Entities"],
        "top_workers_comp_claims": [
            "Volunteer and staff injuries during fundraising events or community outreach",
            "Ergonomic injuries for administrative office workers",
            "Slip-and-fall injuries at program facilities or event venues",
        ],
        "commercial_auto_claims": [
            "Accidents involving staff or volunteers using personal vehicles for organization business",
            "Hired van or bus incidents during program transportation",
        ],
        "general_liability_exposures": [
            "Sexual abuse or molestation claims involving vulnerable populations served",
            "Directors and officers liability for fiduciary mismanagement or governance failures",
            "Event liability for fundraisers, galas, or community gatherings",
            "Professional liability for counseling, mentoring, or advisory services provided",
        ],
        "conversation_prompts": [
            "What populations does your organization serve, and do you work with minors or vulnerable adults?",
            "Do you conduct background checks on all employees and volunteers?",
            "Does the board carry D&O coverage, and what is your annual operating budget?",
            "Do you host public events, and if so, what is the typical attendance?",
        ],
        "regional_risk_notes": "States with extended statutes of limitation for abuse claims (NY, CA, NJ) significantly increase historical liability exposure. Urban nonprofits face higher premises liability frequency than rural counterparts.",
    },
    {
        "industry_name": "Homeless Shelters",
        "synonyms": ["Emergency Shelters", "Transitional Housing Programs", "Homeless Services Providers", "Residential Shelters"],
        "top_workers_comp_claims": [
            "Staff injuries from physical altercations with aggressive or intoxicated residents",
            "Needlestick injuries during facility cleanup or room turnover",
            "Stress-related claims and mental health injuries from high-trauma work environment",
        ],
        "commercial_auto_claims": [
            "Accidents during client transportation to medical appointments or job placements",
            "Van incidents during mobile outreach to encampment sites",
        ],
        "general_liability_exposures": [
            "Assault and battery claims by residents against staff or other residents",
            "Negligent supervision allegations involving vulnerable or mentally ill clients",
            "Communicable disease outbreak liability within congregate living settings",
            "Property damage to neighboring businesses from shelter-adjacent activity",
        ],
        "conversation_prompts": [
            "What is your bed capacity, and do you operate as overnight-only or 24-hour shelter?",
            "Do you have on-site mental health or substance abuse counseling services?",
            "What screening and intake protocols exist for new residents?",
            "Do you have security personnel on-site, and what de-escalation training do staff receive?",
        ],
        "regional_risk_notes": "West Coast cities (LA, Portland, Seattle) and cold-weather metros face extreme capacity pressure increasing operational risk. Local zoning disputes and NIMBY litigation add coverage complexity in suburban expansion areas.",
    },
    {
        "industry_name": "Food Banks",
        "synonyms": ["Food Pantries", "Food Distribution Centers", "Hunger Relief Organizations", "Community Food Programs"],
        "top_workers_comp_claims": [
            "Musculoskeletal injuries from repetitive lifting and sorting of food donations",
            "Forklift and pallet jack injuries in warehouse distribution areas",
            "Volunteer injuries during large-scale food drive sorting events",
        ],
        "commercial_auto_claims": [
            "Refrigerated truck accidents during food pickup and delivery routes",
            "Loading dock incidents during donation intake from grocery and restaurant partners",
        ],
        "general_liability_exposures": [
            "Foodborne illness claims from distribution of spoiled or contaminated products",
            "Slip-and-fall injuries for volunteers and clients at distribution sites",
            "Product liability from donated goods despite Good Samaritan Act protections",
        ],
        "conversation_prompts": [
            "How many pounds of food do you distribute annually, and what percentage is perishable?",
            "Do you operate your own fleet of refrigerated vehicles, or use donated transport?",
            "What food safety and temperature monitoring protocols are in place?",
            "How many volunteers do you use during peak distribution, and are they covered under your policy?",
        ],
        "regional_risk_notes": "Southern and rural food banks cover larger geographic service areas with longer delivery routes, increasing auto exposure. States with weaker Good Samaritan protections expose food banks to greater product liability risk.",
    },
    {
        "industry_name": "Religious Organizations / Churches",
        "synonyms": ["Houses of Worship", "Churches and Ministries", "Faith-Based Organizations", "Congregations", "Temples and Mosques"],
        "top_workers_comp_claims": [
            "Custodial staff injuries from cleaning and facility maintenance tasks",
            "Falls from ladders or elevated surfaces during building upkeep or decoration",
            "Kitchen burns and cuts during meal preparation for community events",
        ],
        "commercial_auto_claims": [
            "Church van or bus accidents during youth group trips or elderly transport",
            "Hired and non-owned auto exposure from clergy and staff using personal vehicles",
        ],
        "general_liability_exposures": [
            "Sexual abuse and molestation claims involving youth ministry programs",
            "Premises liability from slip-and-fall during worship services or events",
            "Counseling liability from pastoral advice on marriage, addiction, or mental health",
            "Property damage or bodily injury during large community events or festivals",
        ],
        "conversation_prompts": [
            "Do you operate youth programs, daycare, or a school, and what safeguarding policies are in place?",
            "Does the church own or regularly use vehicles for ministry transportation?",
            "Do clergy provide formal counseling services, and is there counseling liability coverage?",
            "What is the replacement cost value of the sanctuary and any historic structures?",
        ],
        "regional_risk_notes": "Bible Belt states have larger congregations with more extensive programming, increasing both premises and abuse exposure. Historic churches in the Northeast face elevated property valuations and preservation-related rebuilding costs.",
    },
    {
        "industry_name": "Social Service Agencies",
        "synonyms": ["Human Services Organizations", "Community Service Providers", "Social Work Agencies", "Family Services Organizations"],
        "top_workers_comp_claims": [
            "Caseworker injuries during home visits to volatile or unsafe environments",
            "Stress and burnout-related mental health claims from high caseloads",
            "Motor vehicle accidents during frequent travel between client sites",
        ],
        "commercial_auto_claims": [
            "Accidents during client home visits using agency or personal vehicles",
            "Client transportation incidents for court dates, medical visits, or housing placements",
        ],
        "general_liability_exposures": [
            "Professional liability from failure to report abuse or neglect",
            "Negligent placement or referral claims involving foster care or housing",
            "Breach of confidentiality or privacy violations with sensitive client data",
            "Sexual misconduct allegations by staff or contracted service providers",
        ],
        "conversation_prompts": [
            "What specific populations do you serve — children, elderly, disabled, or justice-involved individuals?",
            "Do caseworkers conduct unsupervised home visits, and what safety protocols exist?",
            "Are you a government contractor, and do your contracts require specific insurance minimums?",
            "What data privacy practices are in place for client records and case files?",
        ],
        "regional_risk_notes": "Agencies operating under state contracts in high-litigation states (FL, CA, NY) face elevated professional liability exposure. Rural agencies cover vast territories, significantly increasing auto exposure for field staff.",
    },
    {
        "industry_name": "Surety and Bonding (Construction)",
        "synonyms": ["Construction Bonding", "Surety Bond Providers", "Contract Surety", "Performance Bond Underwriting"],
        "top_workers_comp_claims": [
            "Office ergonomic injuries for underwriting and administrative staff",
            "Slip-and-fall during site inspections of bonded construction projects",
            "Motor vehicle accidents during travel to contractor or project site meetings",
        ],
        "commercial_auto_claims": [
            "Accidents during field inspections of bonded project sites",
            "Hired and non-owned auto exposure from employees using personal vehicles for client visits",
        ],
        "general_liability_exposures": [
            "Errors and omissions in bond underwriting leading to financial loss for obligees",
            "Failure to properly evaluate contractor financial capacity resulting in bond claims",
            "Vicarious liability allegations from bonded contractor project failures",
            "Regulatory compliance exposure from state insurance department audits",
        ],
        "conversation_prompts": [
            "What is your largest single bond and aggregate bonding capacity currently outstanding?",
            "Do you write primarily contract surety, commercial surety, or court bonds?",
            "What financial underwriting criteria do you use to qualify contractors?",
            "Have you experienced any bond claims or contractor defaults in the past five years?",
        ],
        "regional_risk_notes": "States with prevailing wage and Little Miller Act requirements (most states) mandate bonding on public projects, driving volume. High-growth Sun Belt markets see increased surety demand but also higher contractor default rates during economic downturns.",
    },
    {
        "industry_name": "Auto Body / Collision Shops",
        "synonyms": ["Collision Repair Centers", "Auto Body Repair", "Paint and Body Shops", "Vehicle Restoration Shops"],
        "top_workers_comp_claims": [
            "Respiratory illness from isocyanate exposure in paint spray booth operations",
            "Lacerations and crush injuries from sheet metal work and frame straightening",
            "Chemical burns from solvents, primers, and paint stripping agents",
            "Hearing loss from prolonged use of grinding, sanding, and pneumatic tools",
        ],
        "commercial_auto_claims": [
            "Damage to customer vehicles during test drives or lot movement",
            "Liability from employees driving uninsured customer vehicles on public roads",
            "Accidents involving parts delivery or customer shuttle vehicles",
        ],
        "general_liability_exposures": [
            "Garagekeepers liability for customer vehicles damaged by fire, theft, or vandalism while in shop custody",
            "Faulty repair claims leading to subsequent accidents or component failure",
            "Environmental contamination from paint waste, solvent disposal, or floor drain discharge",
            "Overspray damage to adjacent vehicles or properties",
        ],
        "conversation_prompts": [
            "Are you a DRP (Direct Repair Program) shop for any insurance carriers?",
            "Do you have a compliant spray booth with proper ventilation and fire suppression?",
            "How do you handle hazardous waste disposal for paints, solvents, and body filler?",
            "What is the maximum value of customer vehicles you typically have on premises at any time?",
        ],
        "regional_risk_notes": "Shops in salt belt states (Midwest, Northeast) see higher volume of rust and corrosion repair work. Hail-prone regions (TX, CO, OK) create seasonal volume surges that can strain quality control.",
    },
    {
        "industry_name": "Auto Dealerships",
        "synonyms": ["Car Dealerships", "Automotive Dealers", "New and Used Vehicle Sales", "Franchise Dealers"],
        "top_workers_comp_claims": [
            "Technician injuries from hydraulic lift failures or vehicle falls in service bays",
            "Repetitive motion injuries in service department from tool use",
            "Slip-and-fall on service bay floors with oil or fluid contamination",
        ],
        "commercial_auto_claims": [
            "Test drive accidents involving customers or sales staff",
            "Lot damage from vehicle movement including inventory shuffling and delivery",
            "Dealer plate liability for vehicles operated off premises",
        ],
        "general_liability_exposures": [
            "Premises liability from customer slip-and-fall on showroom or lot surfaces",
            "Product liability from sale of defective vehicles or aftermarket accessories",
            "Garagekeepers liability for customer vehicles in service department custody",
            "Fraud and misrepresentation claims on used vehicle sales history disclosures",
        ],
        "conversation_prompts": [
            "Are you a franchise dealer or independent, and what brands do you carry?",
            "What is your average on-lot inventory value and peak vehicle count?",
            "Do you offer in-house financing, and do you carry dealer E&O coverage?",
            "How many service bays do you operate, and do you perform body work on site?",
        ],
        "regional_risk_notes": "Dealerships in flood-prone and hurricane zones face significant inventory loss exposure from weather events. States with robust lemon laws (CA, MA, CT) increase liability on used vehicle sales.",
    },
    {
        "industry_name": "Cybersecurity Firms",
        "synonyms": ["Information Security Companies", "Cyber Defense Providers", "Security Operations Centers", "Infosec Consultancies"],
        "top_workers_comp_claims": [
            "Ergonomic injuries from extended computer workstation use",
            "Mental health and burnout claims from high-stress incident response work",
            "Travel-related injuries for consultants conducting on-site security assessments",
        ],
        "commercial_auto_claims": [
            "Accidents during travel to client sites for penetration testing or incident response",
            "Hired and non-owned auto exposure for consultants using personal or rental vehicles",
        ],
        "general_liability_exposures": [
            "Technology E&O from failure to detect or prevent a client data breach",
            "Liability from penetration testing activities that inadvertently cause system damage",
            "Breach of confidentiality involving sensitive client vulnerability data",
            "Third-party claims arising from security product or tool recommendations that fail",
        ],
        "conversation_prompts": [
            "Do you perform offensive security services like penetration testing or red teaming?",
            "What contractual liability caps and indemnification terms are in your client agreements?",
            "Do you handle or store client data, including PII or regulated data, during engagements?",
            "Do you carry technology E&O and cyber liability coverage, and what are your current limits?",
        ],
        "regional_risk_notes": "Firms operating in states with strict breach notification laws (CA, NY, TX) face heightened regulatory exposure. DC-metro and Silicon Valley concentrations of federal and enterprise clients bring higher contractual insurance requirements.",
    },
    {
        "industry_name": "IT Managed Service Providers",
        "synonyms": ["MSPs", "IT Services Companies", "Managed IT Providers", "Technology Support Firms", "IT Outsourcing Companies"],
        "top_workers_comp_claims": [
            "Ergonomic injuries from prolonged desk work and workstation setup",
            "Electrical injuries during on-site hardware installation or server maintenance",
            "Slip-and-fall at client premises during service calls",
        ],
        "commercial_auto_claims": [
            "Accidents during travel to client locations for on-site support",
            "Equipment and tool theft from service vehicles",
        ],
        "general_liability_exposures": [
            "Technology E&O from system outages or data loss caused by MSP negligence",
            "Vicarious cyber liability when MSP credentials are used to attack client networks",
            "Failure to apply patches or updates resulting in ransomware or breach at client site",
            "Business interruption claims from clients due to service level agreement failures",
        ],
        "conversation_prompts": [
            "How many client endpoints do you manage, and do you have remote monitoring and management (RMM) tools deployed?",
            "Do you have admin-level access to client networks, and what access controls protect those credentials?",
            "Do your client contracts include SLA penalties, limitation of liability clauses, or cyber incident response obligations?",
            "Have any of your clients experienced a breach that originated from your systems or credentials?",
        ],
        "regional_risk_notes": "MSPs serving healthcare clients in all states must account for HIPAA business associate agreement requirements. Firms serving financial services clients in the Northeast face elevated regulatory compliance demands from NY DFS and SEC cybersecurity rules.",
    },
    {
        "industry_name": "Data Centers",
        "synonyms": ["Colocation Facilities", "Server Farms", "Hosting Facilities", "Cloud Infrastructure Providers"],
        "top_workers_comp_claims": [
            "Electrical shock or arc flash injuries during power distribution maintenance",
            "Heat exhaustion in hot-aisle containment environments during extended maintenance",
            "Ergonomic injuries from lifting and racking heavy server equipment",
        ],
        "commercial_auto_claims": [
            "Accidents involving fuel delivery vehicles for backup generator systems",
            "Equipment transport vehicle incidents during hardware deployment",
        ],
        "general_liability_exposures": [
            "Massive business interruption liability to tenants from power or cooling system failures",
            "Property damage to client equipment from fire suppression system discharge",
            "Environmental liability from diesel fuel storage for backup generators",
            "Consequential loss claims from data loss during outage events",
        ],
        "conversation_prompts": [
            "What is your facility's tier classification and uptime SLA commitment?",
            "What redundancy exists for power (UPS, generators) and cooling systems?",
            "Do you carry sufficient business interruption and contingent business interruption coverage?",
            "What fire suppression system is installed — clean agent, pre-action sprinkler, or both?",
        ],
        "regional_risk_notes": "Data centers in Northern Virginia, Dallas, and Phoenix dominate capacity but face different natural disaster profiles — hurricanes, tornadoes, and extreme heat respectively. Facilities in deregulated energy markets face volatile power cost exposure.",
    },
    {
        "industry_name": "SaaS / Software Companies",
        "synonyms": ["Software as a Service Providers", "Cloud Software Companies", "Application Developers", "Tech Startups"],
        "top_workers_comp_claims": [
            "Repetitive strain and carpal tunnel injuries from continuous keyboard and mouse use",
            "Mental health claims related to workplace stress and demanding release schedules",
            "Slip-and-fall injuries at office or co-working spaces",
        ],
        "commercial_auto_claims": [
            "Accidents during travel to client sites, conferences, or sales meetings",
            "Hired and non-owned auto exposure from employees using ride-share or personal vehicles",
        ],
        "general_liability_exposures": [
            "Technology E&O from software defects causing client financial loss or operational disruption",
            "Intellectual property infringement claims — patent trolls and trade secret disputes",
            "Data breach and privacy liability from handling customer PII or PHI",
            "Media liability from user-generated content hosted on the platform",
        ],
        "conversation_prompts": [
            "What type of data do you process or store for customers — PII, PHI, financial, or payment card data?",
            "Do you carry technology E&O with cyber liability, and are your limits aligned with your largest client contracts?",
            "Have you completed SOC 2 or ISO 27001 certification for your platform?",
            "What is your annual recurring revenue, and do your contracts include limitation of liability clauses?",
        ],
        "regional_risk_notes": "Companies with California presence face CCPA/CPRA compliance exposure, while those serving EU customers need GDPR-aligned coverage. Tech hubs (SF, Austin, NYC, Seattle) have aggressive employment practices liability environments.",
    },
    {
        "industry_name": "Staffing Agencies",
        "synonyms": ["Temporary Employment Agencies", "Staffing Firms", "Employment Services", "Temp Agencies", "PEO Services"],
        "top_workers_comp_claims": [
            "Placed workers injured at client worksites performing unfamiliar tasks with insufficient training",
            "Ergonomic injuries for temp workers in warehouse, manufacturing, or office placements",
            "Slip-and-fall injuries at host employer facilities where staffing agency has limited safety oversight",
            "Repetitive motion injuries from assembly line or data entry assignments",
        ],
        "commercial_auto_claims": [
            "Accidents involving placed workers driving client vehicles or operating mobile equipment",
            "Hired and non-owned auto exposure from recruiters traveling to client sites",
        ],
        "general_liability_exposures": [
            "Co-employment liability for workplace injuries shared with host employers",
            "Employment practices liability for discrimination, harassment, or wrongful termination claims",
            "Negligent hiring and placement claims when placed worker causes harm at client site",
            "Professional liability from failure to properly verify credentials or background checks",
        ],
        "conversation_prompts": [
            "What industries do you staff for — light industrial, clerical, healthcare, or skilled trades?",
            "Do you conduct background checks, drug testing, and skills verification for all placements?",
            "How are workers' comp responsibilities allocated between you and the host employer in your contracts?",
            "What is your annual payroll, and what is the experience modification rate on your workers' comp policy?",
        ],
        "regional_risk_notes": "States with strict co-employment laws (CA, MA, NJ) increase joint liability exposure significantly. Industrial staffing in manufacturing-heavy Midwest states carries higher workers' comp frequency and severity.",
    },
    {
        "industry_name": "Private Security Companies",
        "synonyms": ["Security Guard Services", "Contract Security Firms", "Protective Services", "Security Patrol Companies"],
        "top_workers_comp_claims": [
            "Assault and battery injuries from confrontations with trespassers or aggressors",
            "Slip-and-fall during patrol rounds in poorly lit or uneven environments",
            "Dog bite injuries for K-9 handler operations",
        ],
        "commercial_auto_claims": [
            "Patrol vehicle accidents during mobile security rounds, especially at night",
            "Emergency response driving incidents en route to alarm activations",
            "Property damage from patrol vehicles in parking structures or gated communities",
        ],
        "general_liability_exposures": [
            "Excessive force or false arrest claims by individuals detained by guards",
            "Negligent security allegations when crimes occur at guarded premises",
            "Assault and battery liability from guard misconduct",
            "Failure to report or respond to incidents resulting in third-party harm",
        ],
        "conversation_prompts": [
            "Are your guards armed, and if so, what firearms training and certification do they carry?",
            "Do your contracts include hold-harmless agreements and additional insured requirements from clients?",
            "What screening process do you use — criminal background, drug testing, psychological evaluation?",
            "Do you provide mobile patrol, standing guard, executive protection, or event security?",
        ],
        "regional_risk_notes": "States with strict private security licensing requirements (CA, FL, TX, NY) impose training mandates that affect exposure profile. Armed guard operations in permissive carry states still face significant use-of-force liability.",
    },
    {
        "industry_name": "Armored Car Services",
        "synonyms": ["Cash-in-Transit Services", "Armored Transport", "Valuables Transport", "Secure Courier Services"],
        "top_workers_comp_claims": [
            "Robbery-related assault and gunshot injuries during cash pickups and deliveries",
            "Musculoskeletal injuries from lifting heavy coin bags and currency containers",
            "PTSD and mental health claims following armed robbery attempts",
        ],
        "commercial_auto_claims": [
            "Armored vehicle accidents due to heavy vehicle weight and limited maneuverability",
            "Third-party property damage from large armored trucks in urban environments",
            "Theft and loss of cargo following vehicle breach or hijacking incidents",
        ],
        "general_liability_exposures": [
            "Bailee liability for loss of customer cash and valuables in transit or in vault",
            "Negligent hiring claims when employees are involved in internal theft",
            "Use-of-force liability from armed crew member incidents during robberies",
            "Errors in cash counting, processing, or ATM servicing resulting in client financial loss",
        ],
        "conversation_prompts": [
            "What is the maximum value of cargo carried per vehicle, and what are your vault storage limits?",
            "Are all crew members armed, and what use-of-force training and policies are in place?",
            "What GPS tracking, dual-control, and anti-theft technology is installed in your fleet?",
            "Do you carry crime/fidelity bonds and bailee coverage sufficient for your maximum exposure?",
        ],
        "regional_risk_notes": "Operations in high-crime urban areas (Detroit, St. Louis, Memphis, Baltimore) face elevated robbery risk. Federal Reserve branch locations and cannabis cash-heavy states create unique routing and coverage challenges.",
    },
    {
        "industry_name": "Bail Bonds",
        "synonyms": ["Bail Bond Agencies", "Surety Bail Agents", "Bail Bondsmen", "Fugitive Recovery Services"],
        "top_workers_comp_claims": [
            "Physical assault injuries during fugitive apprehension and recovery operations",
            "Injuries from forcible entry during skip tracing and arrest activities",
            "Motor vehicle accidents during surveillance and pursuit operations",
        ],
        "commercial_auto_claims": [
            "Vehicle accidents during fugitive pursuit or high-speed apprehension scenarios",
            "Surveillance vehicle damage from extended stationary operations in high-crime areas",
        ],
        "general_liability_exposures": [
            "Excessive force and wrongful detention claims during fugitive recovery",
            "Property damage during forced entry at fugitive locations",
            "Civil rights violation allegations from recovery operations",
            "Errors and omissions in bond underwriting or court filing procedures",
        ],
        "conversation_prompts": [
            "Do you employ in-house fugitive recovery agents, or contract with third-party bounty hunters?",
            "What training and licensing do your recovery agents carry, and are they armed?",
            "What is your largest single bond exposure, and what collateral requirements do you enforce?",
            "Have you had any lawsuits related to recovery operations in the past five years?",
        ],
        "regional_risk_notes": "Several states have eliminated or restricted commercial bail bonding (IL, NJ, NM, CA), changing the industry landscape. States allowing bounty hunter operations with minimal oversight (TX, FL) present greater liability exposure.",
    },
    {
        "industry_name": "Property Restoration (Fire/Water)",
        "synonyms": ["Disaster Restoration Companies", "Fire and Water Damage Restoration", "Emergency Restoration Services", "Damage Mitigation Contractors"],
        "top_workers_comp_claims": [
            "Respiratory illness from exposure to smoke residue, asbestos, or mold during demolition",
            "Electrical shock from working in water-damaged structures with compromised wiring",
            "Falls through weakened structural elements in fire-damaged buildings",
            "Chemical exposure from antimicrobial treatments and cleaning agents",
        ],
        "commercial_auto_claims": [
            "Emergency response vehicle accidents during rapid deployment to loss sites",
            "Equipment trailer incidents on highways during mobilization",
            "Theft of extraction and drying equipment from job site vehicles",
        ],
        "general_liability_exposures": [
            "Further property damage caused during restoration work (secondary damage claims)",
            "Failure to properly dry or remediate resulting in mold growth after project completion",
            "Pollution liability from improper disposal of fire debris or contaminated materials",
            "Professional liability from scope of work disputes with insurance adjusters",
        ],
        "conversation_prompts": [
            "Are you IICRC-certified for water damage restoration, fire restoration, and mold remediation?",
            "Do you work primarily with insurance carriers on assignment, or direct to property owners?",
            "What containment and air quality monitoring protocols do you follow on mold and fire jobs?",
            "Do you perform structural repairs, or do you subcontract the rebuild phase?",
        ],
        "regional_risk_notes": "Gulf Coast and Atlantic seaboard companies face extreme seasonal surge demand during hurricane season. Midwest and Southern firms see elevated storm damage volume from tornado and severe thunderstorm events.",
    },
    {
        "industry_name": "Mold Remediation",
        "synonyms": ["Mold Abatement", "Mold Removal Services", "Indoor Air Quality Remediation", "Mold Mitigation Companies"],
        "top_workers_comp_claims": [
            "Respiratory illness from mold spore exposure despite PPE use",
            "Heat-related illness from working in full containment suits in enclosed spaces",
            "Chemical exposure from biocides, fungicides, and antimicrobial treatments",
        ],
        "commercial_auto_claims": [
            "Accidents during travel between remediation job sites with loaded equipment trailers",
            "Equipment damage during transport of air scrubbers and dehumidification units",
        ],
        "general_liability_exposures": [
            "Cross-contamination claims from improper containment spreading mold to unaffected areas",
            "Failure to fully remediate resulting in recurring mold growth and property damage",
            "Third-party bodily injury claims from occupants exposed to mold during or after remediation",
            "Professional liability from inaccurate mold assessments or clearance testing",
        ],
        "conversation_prompts": [
            "Are your technicians certified through IICRC, ACAC, or equivalent mold remediation programs?",
            "Do you perform both mold assessment and remediation, and if so, does your state allow the same firm to do both?",
            "What containment, negative air pressure, and HEPA filtration protocols do you use?",
            "Do you carry a pollution liability policy that specifically covers mold-related claims?",
        ],
        "regional_risk_notes": "Gulf Coast and Southeast states with high humidity (FL, TX, LA, GA) generate the highest remediation demand. States like TX, FL, and NY have specific mold licensing requirements that affect coverage eligibility.",
    },
    {
        "industry_name": "Home Inspection Services",
        "synonyms": ["Residential Inspectors", "Property Inspectors", "Home Inspection Companies", "Building Inspectors"],
        "top_workers_comp_claims": [
            "Falls from roofs, ladders, or attic access points during property inspections",
            "Exposure to asbestos, lead paint, or mold during crawlspace and attic inspections",
            "Animal bites or stings encountered during exterior and crawlspace assessments",
        ],
        "commercial_auto_claims": [
            "Frequent driving accidents between multiple inspection appointments per day",
            "Equipment and tool theft from inspection vehicles",
        ],
        "general_liability_exposures": [
            "Professional liability (E&O) from failure to identify material defects in a property",
            "Negligent misrepresentation claims when buyers discover undisclosed issues post-closing",
            "Property damage caused during inspection — breaking fixtures, damaging surfaces",
            "Third-party reliance claims from real estate agents or lenders on inspection reports",
        ],
        "conversation_prompts": [
            "How many inspections do you perform annually, and what is your average home value inspected?",
            "Do you perform specialty inspections — radon, termite, sewer scope, or pool inspections?",
            "Do your inspection agreements include limitation of liability and arbitration clauses?",
            "Do you carry professional liability (E&O) insurance with adequate limits for your market?",
        ],
        "regional_risk_notes": "States with mandatory inspector licensing (most states now) impose continuing education and standards of practice that affect E&O exposure. Hot real estate markets increase inspection volume and pressure to minimize findings, elevating E&O risk.",
    },
    {
        "industry_name": "Title Companies",
        "synonyms": ["Title Insurance Agencies", "Title and Escrow Companies", "Settlement Service Providers", "Title Abstract Companies"],
        "top_workers_comp_claims": [
            "Ergonomic injuries from extended computer use during title searches and document preparation",
            "Slip-and-fall at office locations or courthouse record rooms",
            "Stress-related claims during high-volume closing periods",
        ],
        "commercial_auto_claims": [
            "Accidents during travel to closings, courthouses, or recording offices",
            "Hired and non-owned auto exposure from mobile notary and closer services",
        ],
        "general_liability_exposures": [
            "Professional liability (E&O) from title search errors resulting in undisclosed liens or encumbrances",
            "Wire fraud and social engineering losses from email compromise during closing transactions",
            "Escrow mishandling or misappropriation of closing funds",
            "Failure to properly record documents resulting in title defects",
        ],
        "conversation_prompts": [
            "What is your annual closing volume and average transaction value?",
            "Do you maintain separate escrow accounts, and are they regularly audited and reconciled?",
            "What wire transfer verification protocols do you have to prevent social engineering fraud?",
            "Do you carry professional liability, fidelity bonds, and cyber liability coverage?",
        ],
        "regional_risk_notes": "Attorney-closing states (Northeast, Southeast) versus escrow-closing states (West) create different operational models and E&O exposure profiles. High-volume markets in FL, TX, and CA face elevated wire fraud targeting.",
    },
    {
        "industry_name": "Real Estate Agencies",
        "synonyms": ["Real Estate Brokerages", "Realty Companies", "Real Estate Firms", "Property Sales Agencies"],
        "top_workers_comp_claims": [
            "Slip-and-fall injuries during property showings at vacant or under-construction homes",
            "Assault or robbery during open houses or private showings",
            "Motor vehicle accidents during frequent travel between listings",
        ],
        "commercial_auto_claims": [
            "Accidents during client property tours and caravan showings",
            "Hired and non-owned auto exposure from agents using personal vehicles",
        ],
        "general_liability_exposures": [
            "Professional liability (E&O) from failure to disclose known property defects",
            "Fair housing discrimination claims related to steering or selective showing practices",
            "Misrepresentation claims on property conditions, zoning, or permitted uses",
            "Breach of fiduciary duty in dual agency or buyer representation situations",
        ],
        "conversation_prompts": [
            "How many agents operate under your brokerage, and are they W-2 employees or independent contractors?",
            "Do you carry brokerage-level E&O, or do individual agents carry their own policies?",
            "What fair housing training do you provide to agents, and how often?",
            "Do you handle property management or commercial transactions in addition to residential sales?",
        ],
        "regional_risk_notes": "High-value markets (coastal CA, NYC, South FL) face larger E&O severity due to transaction sizes. States requiring written buyer agency agreements post-NAR settlement have created new disclosure and compliance exposure.",
    },
    {
        "industry_name": "Mortgage Brokers",
        "synonyms": ["Mortgage Lenders", "Loan Officers", "Mortgage Originators", "Residential Lending Companies"],
        "top_workers_comp_claims": [
            "Ergonomic injuries from prolonged desk and computer work during underwriting",
            "Stress-related claims during high-volume refinance periods",
            "Slip-and-fall at office premises",
        ],
        "commercial_auto_claims": [
            "Accidents during travel to borrower meetings, appraisals, or real estate closings",
            "Hired and non-owned auto exposure from loan officers using personal vehicles",
        ],
        "general_liability_exposures": [
            "Professional liability (E&O) from loan origination errors, rate lock failures, or underwriting mistakes",
            "Fair lending and discrimination claims under ECOA, HMDA, and fair housing regulations",
            "Regulatory enforcement actions from CFPB, state regulators, or HUD",
            "Data breach liability from handling sensitive borrower financial information (SSN, income, assets)",
        ],
        "conversation_prompts": [
            "What is your annual loan origination volume and average loan size?",
            "Are you a broker, correspondent lender, or direct lender, and who are your warehouse line providers?",
            "Do you originate government loans (FHA, VA, USDA) in addition to conventional products?",
            "What compliance management system do you have in place for TRID, RESPA, and fair lending?",
        ],
        "regional_risk_notes": "Brokers in high-cost housing markets (CA, HI, NY, MA) face larger per-loan E&O exposure. States with additional licensing requirements and consumer protection overlays (NY, CA, MA) increase regulatory compliance burden.",
    },
    {
        "industry_name": "Insurance Agencies (E&O)",
        "synonyms": ["Insurance Brokerages", "Independent Insurance Agents", "Insurance Producers", "P&C Insurance Agencies"],
        "top_workers_comp_claims": [
            "Ergonomic injuries from prolonged desk work and computer use",
            "Slip-and-fall injuries at office premises",
            "Motor vehicle accidents during client visits and prospecting",
        ],
        "commercial_auto_claims": [
            "Accidents during travel to client locations for policy reviews and sales appointments",
            "Hired and non-owned auto exposure from producers using personal vehicles",
        ],
        "general_liability_exposures": [
            "Errors and omissions from failure to procure adequate coverage limits or endorsements",
            "Failure to advise on coverage gaps resulting in uninsured losses for clients",
            "Negligent binding authority use resulting in carrier disputes",
            "Data breach liability from handling sensitive policyholder information",
        ],
        "conversation_prompts": [
            "What is your total annual premium volume, and what lines of business do you write?",
            "Do you have formal procedures for documenting client coverage recommendations and declinations?",
            "How many producers and service staff do you employ, and what continuing education do they complete?",
            "Have you had any E&O claims or complaints in the past five years, and what were the circumstances?",
        ],
        "regional_risk_notes": "Agencies in catastrophe-prone states (FL, CA, TX, LA) face heightened E&O exposure from coverage adequacy disputes after major events. States with strong premium finance regulations add compliance complexity.",
    },
]
