TIER_1_INDUSTRIES = [
    {
        "industry_name": "High-Value Residential Property Management",
        "synonyms": [
            "luxury property management",
            "estate management",
            "high-net-worth home management",
            "premium residential management",
        ],
        "top_workers_comp_claims": [
            "Slip-and-fall injuries during property maintenance and groundskeeping",
            "Repetitive strain from cleaning, lifting, and manual upkeep tasks",
            "Injuries from operating power tools and estate maintenance equipment",
        ],
        "commercial_auto_claims": [
            "At-fault collisions while transporting supplies between managed properties",
            "Backing accidents in narrow residential driveways and gated entries",
        ],
        "general_liability_exposures": [
            "Theft or mysterious disappearance claims by homeowners against staff",
            "Property damage during maintenance or renovation oversight",
            "Bodily injury to guests or vendors on managed premises",
            "Errors and omissions in vendor selection leading to substandard work",
        ],
        "conversation_prompts": [
            "What is the total insured value across all properties you manage?",
            "Do you conduct background checks on all staff who access the residences?",
            "How do you handle key control and alarm code management?",
            "Are any properties left vacant for extended periods, and how is vacancy monitored?",
        ],
        "regional_risk_notes": "Coastal and wildfire-prone regions (CA, FL, Outer Banks) carry catastrophic property exposure. Markets with high-net-worth concentrations often require surplus lines placement due to aggregate value.",
    },
    {
        "industry_name": "Short-Term Rental Operations (Airbnb/VRBO)",
        "synonyms": [
            "vacation rental host",
            "Airbnb operator",
            "VRBO host",
            "short-term rental owner",
            "STR operator",
        ],
        "top_workers_comp_claims": [
            "Housekeeping staff injuries from chemical exposure and repetitive cleaning",
            "Back and shoulder strains from linen changes and turnover prep",
            "Slip-and-fall during rapid turnover cleaning between guests",
        ],
        "commercial_auto_claims": [
            "Collisions during urgent supply runs between guest check-out and check-in",
            "Accidents while transporting maintenance equipment to rental units",
        ],
        "general_liability_exposures": [
            "Guest bodily injury from pool, hot tub, deck, or stairway hazards",
            "Property damage or theft by guests exceeding security deposit",
            "Failure to maintain smoke detectors, CO monitors, or fire extinguishers",
            "Liquor liability exposure when properties include stocked bars or beverage amenities",
        ],
        "conversation_prompts": [
            "How many units do you operate, and what is the average nightly occupancy rate?",
            "Do your rental agreements include liability waivers and house rules?",
            "Are pools, hot tubs, or waterfront features present at any properties?",
            "How do you verify compliance with local short-term rental ordinances and permits?",
        ],
        "regional_risk_notes": "Mountain and beach resort markets face seasonal surge exposure. Many municipalities now require STR-specific insurance certificates, and zoning enforcement is tightening in cities like Nashville, New Orleans, and Asheville.",
    },
    {
        "industry_name": "Vacation Rental Management Companies",
        "synonyms": [
            "rental management firm",
            "vacation property manager",
            "resort rental management",
            "holiday rental agency",
        ],
        "top_workers_comp_claims": [
            "Maintenance staff injuries from plumbing, electrical, and appliance repairs across units",
            "Housekeeping repetitive motion injuries at high-turnover volume",
            "Vehicle accidents for staff driving between scattered property locations",
        ],
        "commercial_auto_claims": [
            "Fleet vehicle collisions during peak turnover days with tight schedules",
            "At-fault accidents in unfamiliar resort or rural road conditions",
            "Cargo spills from improperly secured cleaning and maintenance supplies",
        ],
        "general_liability_exposures": [
            "Vicarious liability for guest injuries across a managed portfolio",
            "Professional liability for failing to disclose property defects to guests",
            "Cyber liability from guest payment data and personal information breaches",
            "Contractual liability gaps between property owners and the management company",
        ],
        "conversation_prompts": [
            "How many properties are in your management portfolio, and across how many states?",
            "Do your management agreements clearly allocate insurance responsibilities with property owners?",
            "What is your process for documenting pre-existing property conditions?",
            "Have you experienced any guest injury claims or data breach incidents?",
        ],
        "regional_risk_notes": "Coastal Southeast and mountain resort corridors see the highest claim frequency. Companies managing across state lines face multi-jurisdictional regulatory complexity and differing liability standards.",
    },
    {
        "industry_name": "Mining Operations (Surface)",
        "synonyms": [
            "surface mining",
            "open-pit mining",
            "strip mining",
            "quarry operations",
            "mountaintop mining",
        ],
        "top_workers_comp_claims": [
            "Crush injuries from heavy equipment rollover and haul truck incidents",
            "Hearing loss from prolonged exposure to blasting and crusher noise",
            "Respiratory disease from silica dust and particulate inhalation",
            "Struck-by injuries from falling rock, highwall collapse, or flyrock",
        ],
        "commercial_auto_claims": [
            "Haul truck collisions on mine roads and public highways",
            "Overloaded truck rollovers on steep haul grades",
            "Third-party vehicle damage from rock spillage on public roads",
        ],
        "general_liability_exposures": [
            "Environmental contamination of groundwater and adjacent waterways",
            "Blasting damage to neighboring structures and infrastructure",
            "Trespasser injury on unsecured mine sites",
            "Long-tail occupational disease claims (silicosis, pneumoconiosis)",
        ],
        "conversation_prompts": [
            "What minerals are extracted, and what is your annual tonnage?",
            "Describe your MSHA compliance history and any recent citations",
            "What blasting protocols and flyrock mitigation measures are in place?",
            "Do you have an active reclamation plan and bond in place?",
        ],
        "regional_risk_notes": "Appalachian states (WV, KY, VA) and Western states (WY, MT, NV) dominate this class. MSHA enforcement intensity varies by district, and reclamation bond adequacy is a growing underwriting concern.",
    },
    {
        "industry_name": "Mining Operations (Underground)",
        "synonyms": [
            "underground mining",
            "deep mining",
            "shaft mining",
            "tunnel mining",
            "subsurface mining",
        ],
        "top_workers_comp_claims": [
            "Roof fall and ground collapse injuries causing fatalities and crush trauma",
            "Black lung disease and other chronic respiratory conditions from dust exposure",
            "Explosion and methane ignition burns and blast injuries",
            "Musculoskeletal injuries from working in confined, low-clearance spaces",
        ],
        "commercial_auto_claims": [
            "Surface transport vehicle accidents hauling materials to portal sites",
            "Collisions involving personnel carriers on narrow mine access roads",
        ],
        "general_liability_exposures": [
            "Subsidence damage to surface structures and neighboring properties",
            "Long-tail occupational disease liability spanning decades post-exposure",
            "Environmental discharge from acid mine drainage",
            "Wrongful death litigation from catastrophic mine incidents",
        ],
        "conversation_prompts": [
            "What is the depth and method of extraction (room-and-pillar, longwall, etc.)?",
            "What is your lost-time incident rate over the past five years?",
            "How do you monitor methane levels and ventilation adequacy?",
            "Do you carry mine rescue insurance and participate in a rescue team?",
        ],
        "regional_risk_notes": "Underground coal operations concentrate in Appalachia and Illinois Basin. Hard rock underground mining is prevalent in Nevada, Idaho, and Arizona. These operations face the most restrictive underwriting scrutiny and highest experience modification rates in the mining sector.",
    },
    {
        "industry_name": "Sand and Gravel Extraction",
        "synonyms": [
            "aggregate mining",
            "sand pit operations",
            "gravel quarry",
            "aggregate producer",
        ],
        "top_workers_comp_claims": [
            "Caught-in/between injuries from conveyor systems and screening plants",
            "Silicosis from prolonged respirable crystalline silica exposure",
            "Equipment-related crush injuries during loader and excavator operations",
        ],
        "commercial_auto_claims": [
            "Dump truck rollovers from shifting loads on uneven terrain",
            "Rear-end collisions involving slow-moving loaded trucks on public roads",
            "Tire blowouts on overloaded aggregate haulers causing multi-vehicle accidents",
        ],
        "general_liability_exposures": [
            "Downstream sediment and turbidity pollution in waterways",
            "Noise and dust nuisance complaints from neighboring residents",
            "Trespasser drowning in water-filled exhausted pits",
            "Road damage claims from heavy truck traffic on county roads",
        ],
        "conversation_prompts": [
            "What is your annual extraction volume and number of active pits?",
            "How do you manage dust suppression and silica monitoring?",
            "Are any pits located near residential areas or protected waterways?",
            "What is your conveyor lockout/tagout compliance record?",
        ],
        "regional_risk_notes": "Operations near expanding metro areas face increasing zoning pressure and nuisance litigation. Floodplain pits in the Southeast carry additional environmental permitting complexity.",
    },
    {
        "industry_name": "Municipal Government",
        "synonyms": [
            "city government",
            "town government",
            "municipal operations",
            "local government",
        ],
        "top_workers_comp_claims": [
            "Police and fire line-of-duty injuries including PTSD presumption claims",
            "Public works crew injuries from roadway maintenance and heavy equipment",
            "Sanitation worker musculoskeletal injuries from repetitive lifting",
            "Slip-and-fall injuries in government buildings and maintenance facilities",
        ],
        "commercial_auto_claims": [
            "Emergency vehicle collisions during code-3 response",
            "Municipal fleet accidents involving snowplows, refuse trucks, and utility vehicles",
            "Liability for road defects causing third-party vehicle damage or injury",
        ],
        "general_liability_exposures": [
            "Section 1983 civil rights claims against law enforcement",
            "Premises liability for parks, sidewalks, and public buildings",
            "Wrongful termination and employment practices liability",
            "Failure to maintain infrastructure leading to bodily injury (potholes, fallen trees)",
        ],
        "conversation_prompts": [
            "What is your municipality's population and annual operating budget?",
            "Do you operate your own police department, fire department, or both?",
            "What is your claims history for law enforcement liability in the past five years?",
            "Does the municipality operate any special risk facilities (pools, stadiums, airports)?",
        ],
        "regional_risk_notes": "Tort liability caps vary dramatically by state; some states offer sovereign immunity while others allow unlimited damages. Southern and Western municipalities face growing wildfire and flood infrastructure exposure.",
    },
    {
        "industry_name": "County Government Services",
        "synonyms": [
            "county operations",
            "county administration",
            "county government",
            "parish government",
            "borough government",
        ],
        "top_workers_comp_claims": [
            "Sheriff deputy and corrections officer assault and injury claims",
            "Road crew injuries from heavy equipment and roadside work zone strikes",
            "Courthouse and administrative staff ergonomic and slip-and-fall injuries",
        ],
        "commercial_auto_claims": [
            "Sheriff vehicle pursuit-related collisions",
            "Road maintenance fleet accidents on rural highways",
            "EMS and ambulance transport accidents in adverse weather",
        ],
        "general_liability_exposures": [
            "Jail and detention facility liability (inmate medical care, use of force, suicide)",
            "Land use and zoning decision litigation",
            "Road design and maintenance deficiency claims",
            "Election administration and public records liability",
        ],
        "conversation_prompts": [
            "Does the county operate a jail or detention facility, and what is the average daily population?",
            "How many lane-miles of road does the county maintain?",
            "What is the county's experience with law enforcement liability claims?",
            "Are there any active consent decrees or federal oversight of county operations?",
        ],
        "regional_risk_notes": "Rural counties with large road networks and small budgets carry disproportionate infrastructure liability. Jail liability is the single largest loss driver for many county risk pools, especially in the Southeast.",
    },
    {
        "industry_name": "Public School Districts",
        "synonyms": [
            "K-12 school system",
            "public schools",
            "school board",
            "independent school district",
        ],
        "top_workers_comp_claims": [
            "Teacher and aide injuries from student aggression, especially in special education",
            "Custodial staff slip-and-fall and chemical exposure injuries",
            "Bus driver neck and back injuries from prolonged driving and student management",
            "Athletic trainer and coach injuries during physical education and sports activities",
        ],
        "commercial_auto_claims": [
            "School bus accidents during student transport",
            "District vehicle collisions during extracurricular travel and field trips",
            "Loading zone incidents involving students and bus traffic",
        ],
        "general_liability_exposures": [
            "Sexual abuse and molestation claims against staff or volunteers",
            "Student athletic injury and concussion liability",
            "ADA, Title IX, and civil rights compliance litigation",
            "Playground and facility premises liability",
        ],
        "conversation_prompts": [
            "How many students, campuses, and employees does the district have?",
            "What background check and abuse prevention protocols are in place for all staff and volunteers?",
            "Does the district self-insure or participate in a risk pool?",
            "What is the district's concussion management protocol for athletics?",
        ],
        "regional_risk_notes": "School districts in states without tort caps (e.g., certain Southeastern states) face unlimited verdict exposure. Active shooter and security liability have become top-of-mind underwriting concerns nationwide.",
    },
    {
        "industry_name": "Water and Sewer Utilities",
        "synonyms": [
            "water district",
            "wastewater treatment",
            "water authority",
            "sewer utility",
            "water and wastewater services",
        ],
        "top_workers_comp_claims": [
            "Confined space entry injuries and fatalities in manholes and tanks",
            "Trench collapse injuries during water main and sewer line repair",
            "Chemical burns and toxic gas exposure at treatment facilities",
        ],
        "commercial_auto_claims": [
            "Utility truck collisions during emergency water main break response",
            "Backing accidents with vacuum and jetter trucks in residential areas",
            "Third-party property damage from equipment striking hydrants or meters",
        ],
        "general_liability_exposures": [
            "Waterborne illness outbreak liability from contamination events",
            "Property damage from water main breaks and sewer backups",
            "Environmental liability from wastewater discharge violations",
            "Professional liability for engineering and planning errors in system design",
        ],
        "conversation_prompts": [
            "How many miles of water and sewer lines does the system maintain?",
            "What is the age and condition of the oldest infrastructure in the system?",
            "Have you experienced any boil-water advisories or contamination events?",
            "What is your confined space entry program and compliance history?",
        ],
        "regional_risk_notes": "Aging infrastructure in Southeastern and Appalachian communities creates elevated main break and contamination risk. Western utilities face drought-related supply litigation and increasing regulatory pressure on discharge permits.",
    },
    {
        "industry_name": "Tribal Casino Operations",
        "synonyms": [
            "tribal gaming",
            "Indian casino",
            "Native American gaming",
            "tribal gaming enterprise",
        ],
        "top_workers_comp_claims": [
            "Slip-and-fall injuries on gaming floors from spilled beverages and high foot traffic",
            "Repetitive motion injuries for dealers and slot attendants",
            "Security staff assault and restraint injuries during patron altercations",
            "Kitchen and food service burns, cuts, and ergonomic injuries",
        ],
        "commercial_auto_claims": [
            "Shuttle and courtesy vehicle accidents transporting patrons",
            "Delivery vehicle collisions on reservation roads",
            "Valet parking damage and third-party vehicle claims",
        ],
        "general_liability_exposures": [
            "Patron slip-and-fall and intoxication-related injury claims",
            "Dram shop and liquor liability from on-premises alcohol service",
            "Assault and inadequate security claims in parking structures",
            "Data breach exposure from player loyalty programs and financial transactions",
        ],
        "conversation_prompts": [
            "What is the casino's annual gaming revenue and square footage?",
            "Does the operation include a hotel, restaurant, or entertainment venue?",
            "How is the tribal sovereign immunity waiver structured for commercial activities?",
            "What is the security staffing ratio and surveillance system coverage?",
        ],
        "regional_risk_notes": "Sovereign immunity complicates claims handling and jurisdiction; waivers vary widely by tribe. Oklahoma, California, and the Upper Midwest have the highest density of tribal gaming operations, each with distinct compact structures.",
    },
    {
        "industry_name": "Tribal Government Services",
        "synonyms": [
            "tribal administration",
            "tribal council operations",
            "Native American tribal government",
            "tribal nation services",
        ],
        "top_workers_comp_claims": [
            "Road maintenance and public works injuries on reservation infrastructure",
            "Tribal police and law enforcement line-of-duty injuries",
            "Health clinic staff needle sticks and patient handling injuries",
        ],
        "commercial_auto_claims": [
            "Tribal police vehicle accidents on remote reservation roads",
            "Transport vehicle collisions for elder care and social services programs",
            "Fleet accidents involving poorly maintained reservation roads",
        ],
        "general_liability_exposures": [
            "Premises liability for tribal buildings, community centers, and powwow grounds",
            "Law enforcement excessive force and civil rights allegations",
            "Environmental liability for tribal land contamination and cleanup",
            "Employment practices liability under tribal employment rights ordinances",
        ],
        "conversation_prompts": [
            "What is the enrolled population and number of tribal government employees?",
            "Does the tribe operate its own law enforcement, courts, and health services?",
            "How is sovereign immunity addressed in the tribe's insurance program?",
            "What federal and IHS funding structures support the tribe's risk financing?",
        ],
        "regional_risk_notes": "Tribes in remote areas of the Great Plains and Southwest face limited emergency services access, increasing severity of claims. Federal trust land status creates unique jurisdictional complexities for claims adjusting and litigation.",
    },
    {
        "industry_name": "Tribal Housing Authority",
        "synonyms": [
            "tribal housing",
            "TDHE",
            "tribally designated housing entity",
            "Native American housing authority",
        ],
        "top_workers_comp_claims": [
            "Maintenance worker injuries from electrical, plumbing, and HVAC repair in aging housing stock",
            "Mold-related respiratory illness from remediation work in substandard units",
            "Construction crew injuries during new housing development and renovation projects",
        ],
        "commercial_auto_claims": [
            "Maintenance vehicle accidents on unpaved reservation roads",
            "Collisions during materials delivery to remote housing sites",
        ],
        "general_liability_exposures": [
            "Habitability claims from tenants regarding mold, lead paint, or structural defects",
            "Premises liability for common areas, playgrounds, and community buildings",
            "Fire damage liability from outdated electrical systems in older housing stock",
            "Fair housing and discrimination allegations in tenant selection",
        ],
        "conversation_prompts": [
            "How many housing units does the authority manage, and what is the average age of the housing stock?",
            "What is the current backlog of maintenance and renovation work orders?",
            "Have there been any mold, lead, or habitability complaints or litigation?",
            "What NAHASDA funding level supports your operations and capital improvements?",
        ],
        "regional_risk_notes": "Housing conditions on rural reservations in the Northern Plains and Southwest often involve severe deferred maintenance. Mold and indoor air quality claims are the fastest-growing liability exposure for tribal housing authorities.",
    },
    {
        "industry_name": "Fire Districts / Volunteer Fire Departments",
        "synonyms": [
            "fire protection district",
            "volunteer fire company",
            "rural fire department",
            "fire and rescue district",
        ],
        "top_workers_comp_claims": [
            "Cardiac events and heat-related illness during fireground operations",
            "PTSD and behavioral health claims now covered under presumption laws in many states",
            "Musculoskeletal injuries from equipment handling, hose operations, and ladder work",
            "Cancer presumption claims from chronic smoke and carcinogen exposure",
        ],
        "commercial_auto_claims": [
            "Apparatus collisions during emergency response, especially at intersections",
            "POV accidents by volunteers responding to stations or scenes",
            "Tanker rollover on rural roads during water supply operations",
        ],
        "general_liability_exposures": [
            "Property damage from fireground operations (water damage, forced entry)",
            "Failure to respond or delayed response allegations",
            "Training injury liability for live-fire and technical rescue exercises",
            "Good Samaritan and emergency medical care liability",
        ],
        "conversation_prompts": [
            "What is your call volume, and what percentage is fire versus EMS?",
            "How many career versus volunteer members does the department have?",
            "Does the department provide cancer screening and PFAS decontamination protocols?",
            "What apparatus age and replacement schedule is in place?",
        ],
        "regional_risk_notes": "Wildland-urban interface districts in the West face catastrophic exposure seasons. Southeastern and Appalachian volunteer departments often struggle with aging apparatus and limited training budgets, increasing both frequency and severity of claims.",
    },
    {
        "industry_name": "Public Transit Authorities",
        "synonyms": [
            "mass transit agency",
            "public transportation system",
            "transit district",
            "regional transit authority",
        ],
        "top_workers_comp_claims": [
            "Bus operator assault injuries from passenger altercations",
            "Repetitive vibration and ergonomic injuries from prolonged driving",
            "Maintenance shop injuries from heavy equipment, lifts, and compressed air systems",
        ],
        "commercial_auto_claims": [
            "Bus-pedestrian and bus-cyclist collisions in urban environments",
            "Rear-end and intersection collisions involving fixed-route buses",
            "Passenger injury from sudden stops, falls during boarding, or wheelchair securement failures",
        ],
        "general_liability_exposures": [
            "ADA compliance failures at stops, stations, and on vehicles",
            "Premises liability at transit centers and park-and-ride facilities",
            "Sexual harassment and assault claims by passengers",
            "Environmental contamination from bus depot fuel storage and maintenance operations",
        ],
        "conversation_prompts": [
            "What is the annual ridership and size of the vehicle fleet?",
            "What driver screening, training, and fatigue management programs are in place?",
            "How are assaults on operators tracked and what prevention measures exist?",
            "Does the authority operate paratransit or demand-response services?",
        ],
        "regional_risk_notes": "Urban systems face the highest frequency of pedestrian strikes and operator assaults. Rural and small-city transit systems often rely on older fleets with higher mechanical failure rates, increasing both auto and workers comp claim frequency.",
    },
    {
        "industry_name": "Demolition Contractors",
        "synonyms": [
            "demolition company",
            "wrecking contractor",
            "structural demolition",
            "building demolition services",
        ],
        "top_workers_comp_claims": [
            "Structural collapse and struck-by injuries from uncontrolled falling debris",
            "Respiratory exposure to silica, asbestos, and lead during teardown",
            "Hearing loss from heavy equipment and concrete breaking operations",
            "Crush injuries from excavator and loader operations in tight quarters",
        ],
        "commercial_auto_claims": [
            "Overloaded debris hauling trucks causing tire blowouts and rollovers",
            "Collisions involving oversized equipment transport on public roads",
            "Rear-end accidents from slow-moving loaded dump trucks",
        ],
        "general_liability_exposures": [
            "Damage to adjacent structures from vibration, dust, or uncontrolled collapse",
            "Pollution liability from disturbing contaminated materials (ACM, lead, PCBs)",
            "Injury to bystanders from flyrock or debris projection",
            "Utility strike causing gas leak, electrocution, or service interruption",
        ],
        "conversation_prompts": [
            "What types of structures do you typically demolish (residential, commercial, industrial)?",
            "Do you perform pre-demolition hazmat surveys and abatement in-house?",
            "What is your protocol for utility location and disconnection before work begins?",
            "Have you had any adjacent property damage or pollution claims?",
        ],
        "regional_risk_notes": "Urban demolition in older Northeast and Midwest cities carries the highest asbestos and lead exposure risk. Coastal demolition work may involve additional marine and environmental permitting requirements.",
    },
    {
        "industry_name": "Excavation and Grading",
        "synonyms": [
            "excavation contractor",
            "grading contractor",
            "earthwork contractor",
            "site preparation",
            "dirt work",
        ],
        "top_workers_comp_claims": [
            "Trench collapse and cave-in causing suffocation or crush injuries",
            "Struck-by injuries from backhoe and excavator swing radius",
            "Underground utility strikes resulting in electrocution or gas explosion burns",
        ],
        "commercial_auto_claims": [
            "Dump truck and end-dump trailer rollover on uneven terrain",
            "Accidents during lowboy transport of heavy equipment",
            "Third-party vehicle damage from mud and debris tracked onto public roads",
        ],
        "general_liability_exposures": [
            "Damage to underground utilities (gas, electric, fiber, water)",
            "Stormwater runoff and erosion causing damage to adjacent properties",
            "Foundation and structural damage from vibration or dewatering operations",
            "Third-party injury from unsecured open excavations",
        ],
        "conversation_prompts": [
            "What is the maximum trench depth you typically work at, and what shoring methods do you use?",
            "How do you verify underground utility locations before digging?",
            "Do you perform dewatering, and how is discharge managed?",
            "What is your OSHA trench safety compliance history?",
        ],
        "regional_risk_notes": "Sandy and clay soils in the Southeast increase cave-in risk compared to more stable Western soils. High water table areas along the Gulf Coast and Eastern Seaboard add dewatering complexity and environmental discharge liability.",
    },
    {
        "industry_name": "Masonry Contractors",
        "synonyms": [
            "bricklayer",
            "stone mason",
            "masonry company",
            "block and brick contractor",
        ],
        "top_workers_comp_claims": [
            "Musculoskeletal injuries from repetitive lifting of heavy block and stone",
            "Scaffold falls and ladder falls during wall construction",
            "Silicosis from cutting brick, block, and stone without adequate dust control",
            "Eye injuries from flying chips during cutting and chipping operations",
        ],
        "commercial_auto_claims": [
            "Material delivery truck accidents with heavy palletized loads",
            "Boom truck and telehandler transport incidents on public roads",
        ],
        "general_liability_exposures": [
            "Structural failure of completed masonry walls or facades",
            "Water intrusion claims from faulty flashing or mortar joints",
            "Falling material or tools from scaffolding injuring third parties below",
            "Property damage from scaffold collapse against finished surfaces",
        ],
        "conversation_prompts": [
            "What types of masonry work do you perform (structural, veneer, restoration)?",
            "Do you erect your own scaffolding, or do you subcontract that work?",
            "What is your wet-cutting versus dry-cutting practice for silica compliance?",
            "Have you had any completed operations claims for water intrusion or structural failure?",
        ],
        "regional_risk_notes": "Freeze-thaw cycling in Northern states accelerates completed operations claims for water intrusion. Southeast hurricane zones require enhanced masonry tie and reinforcement standards, increasing both construction cost and defect exposure.",
    },
    {
        "industry_name": "Steel Erection",
        "synonyms": [
            "structural steel contractor",
            "ironworker contractor",
            "steel fabrication and erection",
            "steel erector",
        ],
        "top_workers_comp_claims": [
            "Falls from height during connection work on structural steel",
            "Struck-by injuries from falling beams, tools, or rigging hardware",
            "Crush injuries during crane lifts and steel placement",
            "Burns and eye injuries from welding and cutting operations",
        ],
        "commercial_auto_claims": [
            "Flatbed and lowboy transport accidents hauling structural steel members",
            "Crane mobilization collisions involving oversized loads on highways",
            "Rear-end collisions from slow-moving equipment entering job sites",
        ],
        "general_liability_exposures": [
            "Structural collapse during or after erection causing third-party injury or death",
            "Crane contact with power lines or adjacent structures",
            "Dropped loads injuring other trades on multi-contractor job sites",
            "Completed operations failure leading to building structural deficiency",
        ],
        "conversation_prompts": [
            "What is your maximum working height and typical project size in tonnage?",
            "How do you manage fall protection compliance for connectors and deckers?",
            "What crane operators and rigging certifications do your crews hold?",
            "Describe your steel connection inspection and quality control process.",
        ],
        "regional_risk_notes": "Wind exposure during erection is a major concern in the Great Plains and coastal regions. Urban high-rise steel work in dense cities carries extreme third-party property damage and bodily injury exposure from dropped loads.",
    },
    {
        "industry_name": "Scaffolding Companies",
        "synonyms": [
            "scaffold erector",
            "scaffolding contractor",
            "access solutions provider",
            "scaffold rental and installation",
        ],
        "top_workers_comp_claims": [
            "Falls during scaffold erection, modification, and dismantling",
            "Struck-by injuries from falling scaffold components during assembly",
            "Musculoskeletal injuries from manually carrying and hoisting heavy scaffold tubes and planks",
        ],
        "commercial_auto_claims": [
            "Transport vehicle accidents hauling scaffold equipment to and from job sites",
            "Unsecured load incidents causing scaffold components to fall on roadways",
            "Delivery truck backing accidents at congested construction sites",
        ],
        "general_liability_exposures": [
            "Scaffold collapse causing injury or death to other trades using the scaffold",
            "Property damage to structures from scaffold tie-in points and anchors",
            "Pedestrian injury from falling tools or debris from erected scaffolding",
            "Completed operations liability when scaffold designed or erected defectively",
        ],
        "conversation_prompts": [
            "What types of scaffolding do you erect (frame, systems, suspended, mast-climbing)?",
            "Do you have a competent person program for scaffold design and inspection?",
            "Are your scaffolds designed by a licensed professional engineer when required?",
            "How do you manage other trades' use and modification of your erected scaffolding?",
        ],
        "regional_risk_notes": "High-wind regions require additional engineering for scaffold tie-back and bracing. Coastal and industrial plant maintenance scaffolding in the Gulf Coast faces corrosion-related failure risk and hurricane season exposure.",
    },
    {
        "industry_name": "Environmental Remediation",
        "synonyms": [
            "environmental cleanup",
            "site remediation",
            "hazmat remediation",
            "contaminated site cleanup",
            "brownfield remediation",
        ],
        "top_workers_comp_claims": [
            "Chemical exposure and toxic substance inhalation during soil and groundwater treatment",
            "Heat stress from working in Level A and B PPE suits",
            "Needle sticks and sharps injuries at illegal dumping and clandestine lab cleanup sites",
            "Musculoskeletal injuries from heavy equipment operation in confined or unstable terrain",
        ],
        "commercial_auto_claims": [
            "Hazmat transport vehicle accidents triggering release and spill response",
            "Collisions involving vacuum trucks and tankers carrying contaminated materials",
            "Third-party claims from spills during transport of hazardous waste",
        ],
        "general_liability_exposures": [
            "Pollution legal liability for cross-contamination or incomplete remediation",
            "Professional liability for remediation design errors or sampling failures",
            "Third-party bodily injury from airborne contaminant migration during work",
            "Regulatory liability for improper waste characterization or disposal",
        ],
        "conversation_prompts": [
            "What types of contaminants do you most commonly remediate (petroleum, solvents, metals, PFAS)?",
            "Do you carry contractor's pollution liability with completed operations coverage?",
            "What certifications do your field technicians hold (40-hour HAZWOPER, etc.)?",
            "Have you been involved in any Superfund or state voluntary cleanup program sites?",
        ],
        "regional_risk_notes": "Legacy industrial sites in the Rust Belt and Southeast textile corridor are primary workload drivers. PFAS remediation is an emerging and rapidly growing exposure class with significant long-tail liability uncertainty nationwide.",
    },
    {
        "industry_name": "Asbestos and Lead Abatement",
        "synonyms": [
            "abatement contractor",
            "asbestos removal",
            "lead paint removal",
            "ACM abatement",
            "hazardous material abatement",
        ],
        "top_workers_comp_claims": [
            "Mesothelioma and asbestosis from fiber exposure despite PPE protocols",
            "Lead poisoning from ingestion or inhalation during removal operations",
            "Respiratory distress from inadequate fit-testing or respirator failure",
            "Heat illness from working in full containment with PPE in warm environments",
        ],
        "commercial_auto_claims": [
            "Regulated waste transport vehicle accidents and spill incidents",
            "Collisions during equipment and containment material delivery",
        ],
        "general_liability_exposures": [
            "Third-party exposure claims from containment failure or fiber release",
            "Long-tail disease liability with claims emerging 20-40 years post-exposure",
            "Regulatory fines and penalties for improper removal or disposal methods",
            "Property damage from contamination of unaffected building areas during abatement",
        ],
        "conversation_prompts": [
            "What is your annual volume of abatement projects by type (asbestos, lead, both)?",
            "How do you manage air monitoring and clearance testing during projects?",
            "What is your disposal chain-of-custody process for regulated waste?",
            "Do you carry pollution liability and professional liability with appropriate limits?",
        ],
        "regional_risk_notes": "Pre-1980 building stock in the Northeast, Midwest, and older Southeastern cities generates the highest demand. Long-tail claims from asbestos work make this one of the most difficult classes to place, with many carriers requiring dedicated abatement liability programs.",
    },
    {
        "industry_name": "Well Drilling",
        "synonyms": [
            "water well drilling",
            "well driller",
            "geotechnical drilling",
            "borehole drilling",
            "well installation contractor",
        ],
        "top_workers_comp_claims": [
            "Caught-in injuries from rotating drill rigs and auger equipment",
            "Struck-by injuries from failing drill pipe, tools, or pressurized lines",
            "Back injuries from handling heavy drill rods and casing manually",
        ],
        "commercial_auto_claims": [
            "Drill rig transport accidents on narrow rural roads and soft shoulders",
            "Overweight and oversized load violations causing accidents during mobilization",
            "Support truck collisions while servicing remote drill locations",
        ],
        "general_liability_exposures": [
            "Groundwater contamination from improperly sealed or abandoned wells",
            "Damage to existing wells or aquifers on neighboring properties",
            "Property damage from drilling vibration or fluid circulation",
            "Professional liability for well design, placement, or yield errors",
        ],
        "conversation_prompts": [
            "What types of wells do you drill (water, monitoring, geothermal, geotechnical)?",
            "What is the maximum drilling depth and typical geology you work in?",
            "How do you handle well abandonment and decommissioning?",
            "Have you experienced any claims for groundwater contamination or well interference?",
        ],
        "regional_risk_notes": "Appalachian and Southeastern operations frequently encounter fractured rock aquifers with contamination migration risk. Western states face increasing regulatory scrutiny on water well permitting due to drought and aquifer depletion concerns.",
    },
    {
        "industry_name": "Land Clearing and Forestry Services",
        "synonyms": [
            "land clearing contractor",
            "timber harvesting",
            "forestry operations",
            "logging contractor",
            "right-of-way clearing",
        ],
        "top_workers_comp_claims": [
            "Struck-by injuries from falling trees, limbs, and widow-makers",
            "Chainsaw laceration and kickback injuries",
            "Equipment rollover on steep slopes and uneven terrain",
            "Fatalities from tree felling in unpredictable wind conditions",
        ],
        "commercial_auto_claims": [
            "Log truck rollovers on mountain roads and soft shoulders",
            "Equipment trailer accidents during mobilization on rural highways",
            "Third-party collisions from debris left on roadways after clearing operations",
        ],
        "general_liability_exposures": [
            "Property damage from trees falling onto adjacent structures or utilities",
            "Wildfire liability from equipment sparks or slash pile burning",
            "Environmental damage from erosion and sedimentation after clearing",
            "Damage to underground utilities during stump removal and grubbing",
        ],
        "conversation_prompts": [
            "What types of clearing work do you perform (timber harvest, development clearing, ROW maintenance)?",
            "Do you perform controlled burning, and what fire suppression equipment is on site?",
            "What is your equipment fleet (feller bunchers, skidders, chippers)?",
            "How do you manage erosion control and stormwater on cleared sites?",
        ],
        "regional_risk_notes": "Southeast pine plantation states (GA, AL, MS, SC) and Pacific Northwest timber operations are primary markets. Wildfire liability in Western states has driven massive rate increases and market constriction for any operation involving slash or burn activity.",
    },
    {
        "industry_name": "Bridge and Highway Construction",
        "synonyms": [
            "heavy highway contractor",
            "bridge builder",
            "road construction contractor",
            "infrastructure construction",
            "DOT contractor",
        ],
        "top_workers_comp_claims": [
            "Work zone struck-by injuries from passing motorists and construction equipment",
            "Falls from bridge decks, overpasses, and elevated work platforms",
            "Silicosis and respiratory exposure from concrete cutting and grinding",
            "Hearing loss from pile driving, jackhammering, and heavy equipment operation",
        ],
        "commercial_auto_claims": [
            "Work zone intrusion crashes involving project vehicles and equipment",
            "Dump truck and concrete mixer collisions on active roadways",
            "Equipment transport accidents with oversized loads on interstate highways",
        ],
        "general_liability_exposures": [
            "Third-party motorist injury from inadequate work zone traffic control",
            "Structural defect claims on completed bridges and roadways",
            "Environmental contamination from concrete washout, fuel spills, and dewatering discharge",
            "Delay and consequential damage claims from project owner or public agencies",
        ],
        "conversation_prompts": [
            "What is your typical project size and type (new construction, rehabilitation, widening)?",
            "How do you manage work zone traffic control and temporary traffic management plans?",
            "What is your experience modification rate, and how does it compare to the class average?",
            "Do you perform bridge work over navigable waterways requiring marine insurance?",
        ],
        "regional_risk_notes": "Infrastructure bill funding is driving increased project volume nationwide, but workforce shortages are raising claim frequency among less experienced crews. Freeze-thaw states see accelerated bridge deterioration, increasing rehabilitation project demand in the Northeast and Upper Midwest.",
    },
]
